// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 13:04:06
// Warp portals for Map 3, Zone 19200

using Kakia.TW.World.Scripting;
using static Kakia.TW.World.Scripting.Shortcuts;

namespace Kakia.TW.World.Scripts.Warps
{
    /// <summary>
    /// Warp portals for Map 3, Zone 19200
    /// </summary>
    public class Map3_Zone19200_Warps : NpcScript
    {
        public override void Load()
        {
            // Portal 1059258624 (configured)
            // Area: (368,1032)-(375,1039)
            AddWarp(
                mapId: 3,
                zoneId: 19200,
                minX: 368,
                minY: 1032,
                maxX: 375,
                maxY: 1039,
                destMapId: 3,
                destZoneId: 16640,
                destX: 121,
                destY: 116,
                destDirection: 4
            );

            // Portal 2133000448 (configured)
            // Area: (712,60)-(719,67)
            AddWarp(
                mapId: 3,
                zoneId: 19200,
                minX: 712,
                minY: 60,
                maxX: 719,
                maxY: 67,
                destMapId: 3,
                destZoneId: 19200,
                destX: 685,
                destY: 1039,
                destDirection: 0
            );

            // Portal 3206742272 (configured)
            // Area: (1076,684)-(1083,691)
            AddWarp(
                mapId: 3,
                zoneId: 19200,
                minX: 1076,
                minY: 684,
                maxX: 1083,
                maxY: 691,
                destMapId: 6,
                destZoneId: 38656,
                destX: 149,
                destY: 263,
                destDirection: 4
            );

        }
    }
}
