// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 13:04:06
// Warp portals for Map 3, Zone 24320

using Kakia.TW.World.Scripting;
using static Kakia.TW.World.Scripting.Shortcuts;

namespace Kakia.TW.World.Scripts.Warps
{
    /// <summary>
    /// Warp portals for Map 3, Zone 24320
    /// </summary>
    public class Map3_Zone24320_Warps : NpcScript
    {
        public override void Load()
        {
            // Portal 1878720512 (configured)
            // Area: (160,212)-(167,219)
            AddWarp(
                mapId: 3,
                zoneId: 24320,
                minX: 160,
                minY: 212,
                maxX: 167,
                maxY: 219,
                destMapId: 3,
                destZoneId: 16640,
                destX: 285,
                destY: 245,
                destDirection: 6
            );

            // Portal 2952462336 (configured)
            // Area: (352,188)-(359,195)
            AddWarp(
                mapId: 3,
                zoneId: 24320,
                minX: 352,
                minY: 188,
                maxX: 359,
                maxY: 195,
                destMapId: 3,
                destZoneId: 24320,
                destX: 97,
                destY: 108,
                destDirection: 2
            );

        }
    }
}
