// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 13:04:04
// Warp portals for Map 3, Zone 16640

using Kakia.TW.World.Scripting;
using static Kakia.TW.World.Scripting.Shortcuts;

namespace Kakia.TW.World.Scripts.Warps
{
	/// <summary>
	/// Warp portals for Map 3, Zone 16640
	/// </summary>
	public class Map3_Zone16640_Warps : NpcScript
	{
		public override void Load()
		{
			// Portal 1136460032 (configured)
			// Area: (116,104)-(123,111)
			AddWarp(
				mapId: 3,
				zoneId: 16640,
				minX: 116,
				minY: 104,
				maxX: 123,
				maxY: 111,
				destMapId: 3,
				destZoneId: 19200,
				destX: 369,
				destY: 1026,
				destDirection: 4
			);

			// Portal 3283943680 (configured)
			// Area: (292,244)-(299,251)
			AddWarp(
				mapId: 3,
				zoneId: 16640,
				minX: 292,
				minY: 244,
				maxX: 299,
				maxY: 251,
				destMapId: 3,
				destZoneId: 24320,
				destX: 173,
				destY: 217,
				destDirection: 2
			);

		}
	}
}
