// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 13:04:07
// Warp portals for Map 6, Zone 38656

using Kakia.TW.World.Scripting;
using static Kakia.TW.World.Scripting.Shortcuts;

namespace Kakia.TW.World.Scripts.Warps
{
    /// <summary>
    /// Warp portals for Map 6, Zone 38656
    /// </summary>
    public class Map6_Zone38656_Warps : NpcScript
    {
        public override void Load()
        {
            // Portal 4046323968 (configured)
            // Area: (132,260)-(139,271)
            AddWarp(
                mapId: 6,
                zoneId: 38656,
                minX: 132,
                minY: 260,
                maxX: 139,
                maxY: 271,
                destMapId: 3,
                destZoneId: 19200,
                destX: 1070,
                destY: 690,
                destDirection: 4
            );

            // Portal 1764753664 (configured)
            // Area: (320,212)-(331,223)
            AddWarp(
                mapId: 6,
                zoneId: 38656,
                minX: 320,
                minY: 212,
                maxX: 331,
                maxY: 223,
                destMapId: 6,
                destZoneId: 38144,
                destX: 94,
                destY: 130,
                destDirection: 2
            );

            // Portal 3811574016 (configured)
            // Area: (388,268)-(399,275)
            AddWarp(
                mapId: 6,
                zoneId: 38656,
                minX: 388,
                minY: 268,
                maxX: 399,
                maxY: 275,
                destMapId: 7,
                destZoneId: 1536,
                destX: 94,
                destY: 147,
                destDirection: 2
            );

            // Portal 1664155904 -> Map 403, Portal 343
            SpawnWarp(
                mapId: 6,
                zoneId: 38656,
                x: 384,
                y: 336,
                destMapId: 403,
                destZoneId: 1,
                destX: 100,
                destY: 100
            );

        }
    }
}
