// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 13:04:07
// Warp portals for Map 6, Zone 38144

using Kakia.TW.World.Scripting;
using static Kakia.TW.World.Scripting.Shortcuts;

namespace Kakia.TW.World.Scripts.Warps
{
    /// <summary>
    /// Warp portals for Map 6, Zone 38144
    /// </summary>
    public class Map6_Zone38144_Warps : NpcScript
    {
        public override void Load()
        {
            // Portal 1275396352 (configured)
            // Area: (84,128)-(87,135)
            AddWarp(
                mapId: 6,
                zoneId: 38144,
                minX: 84,
                minY: 128,
                maxX: 87,
                maxY: 135,
                destMapId: 6,
                destZoneId: 38656,
                destX: 302,
                destY: 220,
                destDirection: 6
            );

        }
    }
}
