// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 13:04:07
// Warp portals for Map 7, Zone 1536

using Kakia.TW.World.Scripting;
using static Kakia.TW.World.Scripting.Shortcuts;

namespace Kakia.TW.World.Scripts.Warps
{
    /// <summary>
    /// Warp portals for Map 7, Zone 1536
    /// </summary>
    public class Map7_Zone1536_Warps : NpcScript
    {
        public override void Load()
        {
            // Portal 258474240 (configured)
            // Area: (80,144)-(87,151)
            AddWarp(
                mapId: 7,
                zoneId: 1536,
                minX: 80,
                minY: 144,
                maxX: 87,
                maxY: 151,
                destMapId: 6,
                destZoneId: 38656,
                destX: 382,
                destY: 271,
                destDirection: 6
            );

        }
    }
}
