// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 19:34:43
// Monster spawns for Map 0, Zone 17152

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Spawns
{
    /// <summary>
    /// Monster spawns for Map 0, Zone 17152
    /// </summary>
    public class Map0_Zone17152_Spawns : SpawnScript
    {
        public override void Load()
        {
            // Spawn point 1
            AddSpawner(
                modelId: 2107637,
                name: "Monster_2107637",
                mapId: 0,
                zoneId: 17152,
                x: 1217,
                y: 1280,
                direction: 0,
                respawnTime: 30,
                maxHp: 100
            );

            // Spawn point 2
            AddSpawner(
                modelId: 2107637,
                name: "Monster_2107637",
                mapId: 0,
                zoneId: 17152,
                x: 372,
                y: 71,
                direction: 4,
                respawnTime: 30,
                maxHp: 100
            );

        }
    }
}
