// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 19:34:43
// Monster spawns for Map 0, Zone 3840

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Spawns
{
    /// <summary>
    /// Monster spawns for Map 0, Zone 3840
    /// </summary>
    public class Map0_Zone3840_Spawns : SpawnScript
    {
        public override void Load()
        {
            // Spawn point 1
            AddSpawner(
                modelId: 2100049,
                name: "Monster_2100049",
                mapId: 0,
                zoneId: 3840,
                x: 145,
                y: 205,
                direction: 4,
                respawnTime: 30,
                maxHp: 100
            );

            // Spawn point 2
            AddSpawner(
                modelId: 2100049,
                name: "Monster_2100049",
                mapId: 0,
                zoneId: 3840,
                x: 1217,
                y: 1280,
                direction: 0,
                respawnTime: 30,
                maxHp: 100
            );

            // Spawn point 3
            AddSpawner(
                modelId: 2100049,
                name: "Monster_2100049",
                mapId: 0,
                zoneId: 3840,
                x: 372,
                y: 71,
                direction: 4,
                respawnTime: 30,
                maxHp: 100
            );

        }
    }
}
