// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 19:34:44
// Monster spawns for Map 3, Zone 19456

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Spawns
{
    /// <summary>
    /// Monster spawns for Map 3, Zone 19456
    /// </summary>
    public class Map3_Zone19456_Spawns : SpawnScript
    {
        public override void Load()
        {
            // Spawn point 1
            AddSpawner(
                modelId: 2101401,
                name: "Monster_2101401",
                mapId: 3,
                zoneId: 19456,
                x: 685,
                y: 1039,
                direction: 0,
                respawnTime: 30,
                maxHp: 100
            );

        }
    }
}
