// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 19:34:44
// Monster spawns for Map 3, Zone 19200

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Spawns
{
    /// <summary>
    /// Monster spawns for Map 3, Zone 19200
    /// </summary>
    public class Map3_Zone19200_Spawns : SpawnScript
    {
        public override void Load()
        {
            // Spawn point 1
            AddSpawner(
                modelId: 2101251,
                name: "Monster_2101251",
                mapId: 3,
                zoneId: 19200,
                x: 374,
                y: 1025,
                direction: 4,
                respawnTime: 30,
                maxHp: 100
            );

            // Spawn point 2
            AddSpawner(
                modelId: 2101138,
                name: "Monster_2101138",
                mapId: 3,
                zoneId: 19200,
                x: 371,
                y: 1026,
                direction: 4,
                respawnTime: 30,
                maxHp: 100
            );

            // Spawn point 3
            AddSpawner(
                modelId: 2101138,
                name: "Monster_2101138",
                mapId: 3,
                zoneId: 19200,
                x: 373,
                y: 1024,
                direction: 4,
                respawnTime: 30,
                maxHp: 100
            );

            // Spawn point 4
            AddSpawner(
                modelId: 2101251,
                name: "Monster_2101251",
                mapId: 3,
                zoneId: 19200,
                x: 371,
                y: 1025,
                direction: 4,
                respawnTime: 30,
                maxHp: 100
            );

            // Spawn point 5
            AddSpawner(
                modelId: 2101138,
                name: "Monster_2101138",
                mapId: 3,
                zoneId: 19200,
                x: 1069,
                y: 688,
                direction: 4,
                respawnTime: 30,
                maxHp: 100
            );

            // Spawn point 6
            AddSpawner(
                modelId: 2101138,
                name: "Monster_2101138",
                mapId: 3,
                zoneId: 19200,
                x: 1070,
                y: 690,
                direction: 4,
                respawnTime: 30,
                maxHp: 100
            );

            // Spawn point 7
            AddSpawner(
                modelId: 2101251,
                name: "Monster_2101251",
                mapId: 3,
                zoneId: 19200,
                x: 369,
                y: 1026,
                direction: 4,
                respawnTime: 30,
                maxHp: 100
            );

            // Spawn point 8
            AddSpawner(
                modelId: 2100057,
                name: "Monster_2100057",
                mapId: 3,
                zoneId: 19200,
                x: 685,
                y: 1039,
                direction: 0,
                respawnTime: 30,
                maxHp: 100
            );

        }
    }
}
