// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 19:34:44
// Monster spawns for Map 7, Zone 1536

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Spawns
{
    /// <summary>
    /// Monster spawns for Map 7, Zone 1536
    /// </summary>
    public class Map7_Zone1536_Spawns : SpawnScript
    {
        public override void Load()
        {
            // Spawn point 1
            AddSpawner(
                modelId: 2105070,
                name: "Monster_2105070",
                mapId: 7,
                zoneId: 1536,
                x: 92,
                y: 143,
                direction: 2,
                respawnTime: 30,
                maxHp: 100
            );

            // Spawn point 2
            AddSpawner(
                modelId: 2105071,
                name: "Monster_2105071",
                mapId: 7,
                zoneId: 1536,
                x: 85,
                y: 117,
                direction: 0,
                respawnTime: 30,
                maxHp: 100
            );

            // Spawn point 3
            AddSpawner(
                modelId: 2105070,
                name: "Monster_2105070",
                mapId: 7,
                zoneId: 1536,
                x: 164,
                y: 159,
                direction: 4,
                respawnTime: 30,
                maxHp: 100
            );

            // Spawn point 4
            AddSpawner(
                modelId: 2105071,
                name: "Monster_2105071",
                mapId: 7,
                zoneId: 1536,
                x: 93,
                y: 141,
                direction: 2,
                respawnTime: 30,
                maxHp: 100
            );

            // Spawn point 5
            AddSpawner(
                modelId: 2105070,
                name: "Monster_2105070",
                mapId: 7,
                zoneId: 1536,
                x: 87,
                y: 118,
                direction: 0,
                respawnTime: 30,
                maxHp: 100
            );

            // Spawn point 6
            AddSpawner(
                modelId: 2105071,
                name: "Monster_2105071",
                mapId: 7,
                zoneId: 1536,
                x: 167,
                y: 158,
                direction: 4,
                respawnTime: 30,
                maxHp: 100
            );

            // Spawn point 7
            AddSpawner(
                modelId: 2105070,
                name: "Monster_2105070",
                mapId: 7,
                zoneId: 1536,
                x: 94,
                y: 147,
                direction: 2,
                respawnTime: 30,
                maxHp: 100
            );

        }
    }
}
