// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 14:16:02
// NPCs for Map 0, Zone 17152

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Npcs
{
    /// <summary>
    /// NPCs for Map 0, Zone 17152
    /// </summary>
    public class Map0_Zone17152_Npcs : NpcScript
    {
        public override void Load()
        {
            // ObjectID: 2646150920, ModelID: 2107637
            SpawnNpc(
                modelId: 2107637,
                name: "NPC_2107637",
                mapId: 0,
                zoneId: 17152,
                x: 1137,
                y: 1207,
                direction: 3,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 3094351880, ModelID: 2107637
            SpawnNpc(
                modelId: 2107637,
                name: "NPC_2107637",
                mapId: 0,
                zoneId: 17152,
                x: 1192,
                y: 1206,
                direction: 3,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 1857228808, ModelID: 2107637
            SpawnNpc(
                modelId: 2107637,
                name: "NPC_2107637",
                mapId: 0,
                zoneId: 17152,
                x: 1148,
                y: 1178,
                direction: 5,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 3534129706, ModelID: 2107637
            SpawnNpc(
                modelId: 2107637,
                name: "NPC_2107637",
                mapId: 0,
                zoneId: 17152,
                x: 1149,
                y: 1199,
                direction: 7,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 4103838000, ModelID: 2107637
            SpawnNpc(
                modelId: 2107637,
                name: "NPC_2107637",
                mapId: 0,
                zoneId: 17152,
                x: 1182,
                y: 1240,
                direction: 3,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 358914608, ModelID: 2107637
            SpawnNpc(
                modelId: 2107637,
                name: "NPC_2107637",
                mapId: 0,
                zoneId: 17152,
                x: 1163,
                y: 1231,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 1804820536, ModelID: 2107637
            SpawnNpc(
                modelId: 2107637,
                name: "NPC_2107637",
                mapId: 0,
                zoneId: 17152,
                x: 1136,
                y: 1194,
                direction: 6,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 2559795256, ModelID: 2107637
            SpawnNpc(
                modelId: 2107637,
                name: "NPC_2107637",
                mapId: 0,
                zoneId: 17152,
                x: 1132,
                y: 1173,
                direction: 5,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 3467010104, ModelID: 2107637
            SpawnNpc(
                modelId: 2107637,
                name: "NPC_2107637",
                mapId: 0,
                zoneId: 17152,
                x: 1128,
                y: 1209,
                direction: 6,
                dialogFunc: null  // TODO: Add dialog
            );

        }
    }
}
