// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 14:16:02
// NPCs for Map 0, Zone 3840

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Npcs
{
    /// <summary>
    /// NPCs for Map 0, Zone 3840
    /// </summary>
    public class Map0_Zone3840_Npcs : NpcScript
    {
        public override void Load()
        {
            // ObjectID: 183924, ModelID: 2203131
            SpawnNpc(
                modelId: 2203131,
                name: "NPC_2203131",
                mapId: 0,
                zoneId: 3840,
                x: 217,
                y: 240,
                direction: 1,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 183929, ModelID: 2201820
            SpawnNpc(
                modelId: 2201820,
                name: "NPC_2201820",
                mapId: 0,
                zoneId: 3840,
                x: 120,
                y: 209,
                direction: 4,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 183954, ModelID: 2200804
            SpawnNpc(
                modelId: 2200804,
                name: "NPC_2200804",
                mapId: 0,
                zoneId: 3840,
                x: 211,
                y: 231,
                direction: 4,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 184064, ModelID: 2200803
            SpawnNpc(
                modelId: 2200803,
                name: "NPC_2200803",
                mapId: 0,
                zoneId: 3840,
                x: 223,
                y: 246,
                direction: 6,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 184069, ModelID: 2201164
            SpawnNpc(
                modelId: 2201164,
                name: "NPC_2201164",
                mapId: 0,
                zoneId: 3840,
                x: 223,
                y: 168,
                direction: 6,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 184079, ModelID: 2200715
            SpawnNpc(
                modelId: 2200715,
                name: "NPC_2200715",
                mapId: 0,
                zoneId: 3840,
                x: 331,
                y: 247,
                direction: 1,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 184115, ModelID: 2200139
            SpawnNpc(
                modelId: 2200139,
                name: "NPC_2200139",
                mapId: 0,
                zoneId: 3840,
                x: 175,
                y: 258,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 184120, ModelID: 2200138
            SpawnNpc(
                modelId: 2200138,
                name: "NPC_2200138",
                mapId: 0,
                zoneId: 3840,
                x: 242,
                y: 90,
                direction: 3,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 184125, ModelID: 2200075
            SpawnNpc(
                modelId: 2200075,
                name: "NPC_2200075",
                mapId: 0,
                zoneId: 3840,
                x: 228,
                y: 274,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 184130, ModelID: 2200085
            SpawnNpc(
                modelId: 2200085,
                name: "NPC_2200085",
                mapId: 0,
                zoneId: 3840,
                x: 163,
                y: 107,
                direction: 4,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 184135, ModelID: 2200084
            SpawnNpc(
                modelId: 2200084,
                name: "NPC_2200084",
                mapId: 0,
                zoneId: 3840,
                x: 167,
                y: 107,
                direction: 4,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 184140, ModelID: 2200083
            SpawnNpc(
                modelId: 2200083,
                name: "NPC_2200083",
                mapId: 0,
                zoneId: 3840,
                x: 171,
                y: 107,
                direction: 4,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 184145, ModelID: 2200082
            SpawnNpc(
                modelId: 2200082,
                name: "NPC_2200082",
                mapId: 0,
                zoneId: 3840,
                x: 174,
                y: 107,
                direction: 4,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 3167683072, ModelID: 2100049
            SpawnNpc(
                modelId: 2100049,
                name: "NPC_2100049",
                mapId: 0,
                zoneId: 3840,
                x: 282,
                y: 172,
                direction: 2,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 3251569152, ModelID: 2100049
            SpawnNpc(
                modelId: 2100049,
                name: "NPC_2100049",
                mapId: 0,
                zoneId: 3840,
                x: 336,
                y: 147,
                direction: 3,
                dialogFunc: null  // TODO: Add dialog
            );

        }
    }
}
