// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 14:16:02
// NPCs for Map 3, Zone 19200

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Npcs
{
    /// <summary>
    /// NPCs for Map 3, Zone 19200
    /// </summary>
    public class Map3_Zone19200_Npcs : NpcScript
    {
        public override void Load()
        {
            // ObjectID: 174814, ModelID: 2202477
            SpawnNpc(
                modelId: 2202477,
                name: "NPC_2202477",
                mapId: 3,
                zoneId: 19200,
                x: 1082,
                y: 509,
                direction: 6,
                dialogFunc: null  // TODO: Add dialog
            );

        }
    }
}
