// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 13:04:06
// NPCs for Map 3, Zone 26624

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Npcs
{
    /// <summary>
    /// NPCs for Map 3, Zone 26624
    /// </summary>
    public class Map3_Zone26624_Npcs : NpcScript
    {
        public override void Load()
        {
            // ObjectID: 174421, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 26624,
                x: 83,
                y: 625,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 174426, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 26624,
                x: 108,
                y: 1649,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

        }
    }
}
