// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 13:04:06
// NPCs for Map 3, Zone 24576

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Npcs
{
    /// <summary>
    /// NPCs for Map 3, Zone 24576
    /// </summary>
    public class Map3_Zone24576_Npcs : NpcScript
    {
        public override void Load()
        {
            // ObjectID: 174536, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 24576,
                x: 135,
                y: 1127,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

        }
    }
}
