// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 13:04:06
// NPCs for Map 3, Zone 26368

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Npcs
{
    /// <summary>
    /// NPCs for Map 3, Zone 26368
    /// </summary>
    public class Map3_Zone26368_Npcs : NpcScript
    {
        public override void Load()
        {
            // ObjectID: 174431, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 26368,
                x: 90,
                y: 1129,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 174436, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 26368,
                x: 130,
                y: 1123,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 174441, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 26368,
                x: 120,
                y: 1123,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 174446, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 26368,
                x: 120,
                y: 114,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 174451, ModelID: 37665
            SpawnNpc(
                modelId: 37665,
                name: "NPC_37665",
                mapId: 3,
                zoneId: 26368,
                x: 145,
                y: 100,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 174456, ModelID: 37665
            SpawnNpc(
                modelId: 37665,
                name: "NPC_37665",
                mapId: 3,
                zoneId: 26368,
                x: 146,
                y: 1641,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

        }
    }
}
