// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 13:04:06
// NPCs for Map 3, Zone 24832

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Npcs
{
    /// <summary>
    /// NPCs for Map 3, Zone 24832
    /// </summary>
    public class Map3_Zone24832_Npcs : NpcScript
    {
        public override void Load()
        {
            // ObjectID: 174516, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 24832,
                x: 139,
                y: 1128,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 174521, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 24832,
                x: 133,
                y: 153,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 174526, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 24832,
                x: 152,
                y: 1653,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 174531, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 24832,
                x: 152,
                y: 1646,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

        }
    }
}
