// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 14:16:02
// NPCs for Map 3, Zone 19456

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Npcs
{
    /// <summary>
    /// NPCs for Map 3, Zone 19456
    /// </summary>
    public class Map3_Zone19456_Npcs : NpcScript
    {
        public override void Load()
        {
            // ObjectID: 344139044, ModelID: 2101401
            SpawnNpc(
                modelId: 2101401,
                name: "NPC_2101401",
                mapId: 3,
                zoneId: 19456,
                x: 628,
                y: 879,
                direction: 6,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 1421603621, ModelID: 2101400
            SpawnNpc(
                modelId: 2101400,
                name: "NPC_2101400",
                mapId: 3,
                zoneId: 19456,
                x: 695,
                y: 872,
                direction: 7,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 1227486245, ModelID: 2107978
            SpawnNpc(
                modelId: 2107978,
                name: "NPC_2107978",
                mapId: 3,
                zoneId: 19456,
                x: 748,
                y: 913,
                direction: 3,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 2419289382, ModelID: 2101400
            SpawnNpc(
                modelId: 2101400,
                name: "NPC_2101400",
                mapId: 3,
                zoneId: 19456,
                x: 641,
                y: 975,
                direction: 5,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 2732501286, ModelID: 2107978
            SpawnNpc(
                modelId: 2107978,
                name: "NPC_2107978",
                mapId: 3,
                zoneId: 19456,
                x: 636,
                y: 898,
                direction: 1,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 259625767, ModelID: 2101402
            SpawnNpc(
                modelId: 2101402,
                name: "NPC_2101402",
                mapId: 3,
                zoneId: 19456,
                x: 687,
                y: 946,
                direction: 1,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 2699210023, ModelID: 2101402
            SpawnNpc(
                modelId: 2101402,
                name: "NPC_2101402",
                mapId: 3,
                zoneId: 19456,
                x: 736,
                y: 986,
                direction: 4,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 4161126951, ModelID: 2101400
            SpawnNpc(
                modelId: 2101400,
                name: "NPC_2101400",
                mapId: 3,
                zoneId: 19456,
                x: 725,
                y: 889,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 2817985321, ModelID: 2101402
            SpawnNpc(
                modelId: 2101402,
                name: "NPC_2101402",
                mapId: 3,
                zoneId: 19456,
                x: 743,
                y: 966,
                direction: 2,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 542793780, ModelID: 2101139
            SpawnNpc(
                modelId: 2101139,
                name: "NPC_2101139",
                mapId: 3,
                zoneId: 19456,
                x: 684,
                y: 936,
                direction: 6,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 2426233396, ModelID: 2101402
            SpawnNpc(
                modelId: 2101402,
                name: "NPC_2101402",
                mapId: 3,
                zoneId: 19456,
                x: 738,
                y: 966,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 394756664, ModelID: 2101402
            SpawnNpc(
                modelId: 2101402,
                name: "NPC_2101402",
                mapId: 3,
                zoneId: 19456,
                x: 752,
                y: 979,
                direction: 1,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 4055207736, ModelID: 2101402
            SpawnNpc(
                modelId: 2101402,
                name: "NPC_2101402",
                mapId: 3,
                zoneId: 19456,
                x: 651,
                y: 952,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 2716176696, ModelID: 2101402
            SpawnNpc(
                modelId: 2101402,
                name: "NPC_2101402",
                mapId: 3,
                zoneId: 19456,
                x: 736,
                y: 989,
                direction: 1,
                dialogFunc: null  // TODO: Add dialog
            );

        }
    }
}
