// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 13:04:06
// NPCs for Map 3, Zone 28160

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Npcs
{
    /// <summary>
    /// NPCs for Map 3, Zone 28160
    /// </summary>
    public class Map3_Zone28160_Npcs : NpcScript
    {
        public override void Load()
        {
            // ObjectID: 174361, ModelID: 37665
            SpawnNpc(
                modelId: 37665,
                name: "NPC_37665",
                mapId: 3,
                zoneId: 28160,
                x: 117,
                y: 1648,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

        }
    }
}
