// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 13:04:04
// NPCs for Map 3, Zone 18176

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Npcs
{
    /// <summary>
    /// NPCs for Map 3, Zone 18176
    /// </summary>
    public class Map3_Zone18176_Npcs : NpcScript
    {
        public override void Load()
        {
            // ObjectID: 174835, ModelID: 39713
            SpawnNpc(
                modelId: 39713,
                name: "NPC_39713",
                mapId: 3,
                zoneId: 18176,
                x: 74,
                y: 1155,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 174945, ModelID: 39713
            SpawnNpc(
                modelId: 39713,
                name: "NPC_39713",
                mapId: 3,
                zoneId: 18176,
                x: 77,
                y: 134,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 174950, ModelID: 38433
            SpawnNpc(
                modelId: 38433,
                name: "NPC_38433",
                mapId: 3,
                zoneId: 18176,
                x: 65,
                y: 135,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 174955, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 18176,
                x: 107,
                y: 353,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 174960, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 18176,
                x: 70,
                y: 1146,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 174965, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 18176,
                x: 100,
                y: 1663,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 174970, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 18176,
                x: 115,
                y: 1647,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 174975, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 18176,
                x: 93,
                y: 363,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 174980, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 18176,
                x: 88,
                y: 362,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 174985, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 18176,
                x: 107,
                y: 1641,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

        }
    }
}
