// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 13:04:04
// NPCs for Map 3, Zone 17664

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Npcs
{
    /// <summary>
    /// NPCs for Map 3, Zone 17664
    /// </summary>
    public class Map3_Zone17664_Npcs : NpcScript
    {
        public override void Load()
        {
            // ObjectID: 175027, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 17664,
                x: 113,
                y: 1138,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 175032, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 17664,
                x: 112,
                y: 1117,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 175037, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 17664,
                x: 117,
                y: 1634,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

        }
    }
}
