// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 13:04:06
// NPCs for Map 3, Zone 24320

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Npcs
{
    /// <summary>
    /// NPCs for Map 3, Zone 24320
    /// </summary>
    public class Map3_Zone24320_Npcs : NpcScript
    {
        public override void Load()
        {
            // ObjectID: 174669, ModelID: 39969
            SpawnNpc(
                modelId: 39969,
                name: "NPC_39969",
                mapId: 3,
                zoneId: 24320,
                x: 14,
                y: 1728,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 174674, ModelID: 39969
            SpawnNpc(
                modelId: 39969,
                name: "NPC_39969",
                mapId: 3,
                zoneId: 24320,
                x: 14,
                y: 1736,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 174679, ModelID: 39201
            SpawnNpc(
                modelId: 39201,
                name: "NPC_39201",
                mapId: 3,
                zoneId: 24320,
                x: 13,
                y: 1749,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 174684, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 24320,
                x: 6,
                y: 1185,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 174689, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 24320,
                x: 100,
                y: 1209,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 174694, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 24320,
                x: 105,
                y: 1726,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

        }
    }
}
