// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 13:04:06
// NPCs for Map 3, Zone 26112

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Npcs
{
    /// <summary>
    /// NPCs for Map 3, Zone 26112
    /// </summary>
    public class Map3_Zone26112_Npcs : NpcScript
    {
        public override void Load()
        {
            // ObjectID: 174461, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 26112,
                x: 111,
                y: 1123,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 174466, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 26112,
                x: 117,
                y: 1641,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

        }
    }
}
