// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 13:04:04
// NPCs for Map 3, Zone 17920

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Npcs
{
    /// <summary>
    /// NPCs for Map 3, Zone 17920
    /// </summary>
    public class Map3_Zone17920_Npcs : NpcScript
    {
        public override void Load()
        {
            // ObjectID: 175006, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 17920,
                x: 100,
                y: 1656,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

        }
    }
}
