// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 13:04:04
// NPCs for Map 3, Zone 16640

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Npcs
{
    /// <summary>
    /// NPCs for Map 3, Zone 16640
    /// </summary>
    public class Map3_Zone16640_Npcs : NpcScript
    {
        public override void Load()
        {
            // ObjectID: 136258, ModelID: 38177
            SpawnNpc(
                modelId: 38177,
                name: "NPC_38177",
                mapId: 3,
                zoneId: 16640,
                x: 241,
                y: 734,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 136263, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 16640,
                x: 147,
                y: 1760,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 136268, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 16640,
                x: 245,
                y: 1791,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 136273, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 16640,
                x: 224,
                y: 1759,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 136278, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 16640,
                x: 227,
                y: 1759,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 136283, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 16640,
                x: 350,
                y: 1078,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 136288, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 16640,
                x: 120,
                y: 200,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 136293, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 16640,
                x: 252,
                y: 1243,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 136298, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 16640,
                x: 30,
                y: 1775,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 136303, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 16640,
                x: 286,
                y: 1536,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

        }
    }
}
