// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 13:04:06
// NPCs for Map 3, Zone 46848

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Npcs
{
    /// <summary>
    /// NPCs for Map 3, Zone 46848
    /// </summary>
    public class Map3_Zone46848_Npcs : NpcScript
    {
        public override void Load()
        {
            // ObjectID: 174091, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 46848,
                x: 114,
                y: 1643,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

        }
    }
}
