// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 13:04:04
// NPCs for Map 3, Zone 17408

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Npcs
{
    /// <summary>
    /// NPCs for Map 3, Zone 17408
    /// </summary>
    public class Map3_Zone17408_Npcs : NpcScript
    {
        public override void Load()
        {
            // ObjectID: 175097, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 17408,
                x: 91,
                y: 1137,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 175102, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 17408,
                x: 111,
                y: 1649,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 175107, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 17408,
                x: 102,
                y: 1129,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

        }
    }
}
