// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 13:04:06
// NPCs for Map 3, Zone 27904

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Npcs
{
    /// <summary>
    /// NPCs for Map 3, Zone 27904
    /// </summary>
    public class Map3_Zone27904_Npcs : NpcScript
    {
        public override void Load()
        {
            // ObjectID: 174366, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 27904,
                x: 106,
                y: 1652,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 174371, ModelID: 37921
            SpawnNpc(
                modelId: 37921,
                name: "NPC_37921",
                mapId: 3,
                zoneId: 27904,
                x: 106,
                y: 1646,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

        }
    }
}
