// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 13:28:14
// NPCs for Map 6, Zone 38656

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Npcs
{
    /// <summary>
    /// NPCs for Map 6, Zone 38656
    /// </summary>
    public class Map6_Zone38656_Npcs : NpcScript
    {
        public override void Load()
        {
            // ObjectID: 133628, ModelID: 2203235
            SpawnNpc(
                modelId: 2203235,
                name: "NPC_2203235",
                mapId: 6,
                zoneId: 38656,
                x: 267,
                y: 306,
                direction: 4,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133638, ModelID: 2203425
            SpawnNpc(
                modelId: 2203425,
                name: "NPC_2203425",
                mapId: 6,
                zoneId: 38656,
                x: 271,
                y: 260,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133643, ModelID: 2201600
            SpawnNpc(
                modelId: 2201600,
                name: "NPC_2201600",
                mapId: 6,
                zoneId: 38656,
                x: 267,
                y: 218,
                direction: 6,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133648, ModelID: 2200790
            SpawnNpc(
                modelId: 2200790,
                name: "NPC_2200790",
                mapId: 6,
                zoneId: 38656,
                x: 266,
                y: 319,
                direction: 6,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133653, ModelID: 2202717
            SpawnNpc(
                modelId: 2202717,
                name: "NPC_2202717",
                mapId: 6,
                zoneId: 38656,
                x: 419,
                y: 319,
                direction: 6,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133658, ModelID: 2200569
            SpawnNpc(
                modelId: 2200569,
                name: "NPC_2200569",
                mapId: 6,
                zoneId: 38656,
                x: 312,
                y: 277,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133663, ModelID: 2202536
            SpawnNpc(
                modelId: 2202536,
                name: "NPC_2202536",
                mapId: 6,
                zoneId: 38656,
                x: 366,
                y: 309,
                direction: 4,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133668, ModelID: 2202489
            SpawnNpc(
                modelId: 2202489,
                name: "NPC_2202489",
                mapId: 6,
                zoneId: 38656,
                x: 362,
                y: 260,
                direction: 4,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133673, ModelID: 2201605
            SpawnNpc(
                modelId: 2201605,
                name: "NPC_2201605",
                mapId: 6,
                zoneId: 38656,
                x: 433,
                y: 302,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133678, ModelID: 2201604
            SpawnNpc(
                modelId: 2201604,
                name: "NPC_2201604",
                mapId: 6,
                zoneId: 38656,
                x: 325,
                y: 242,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133683, ModelID: 2201603
            SpawnNpc(
                modelId: 2201603,
                name: "NPC_2201603",
                mapId: 6,
                zoneId: 38656,
                x: 292,
                y: 263,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133688, ModelID: 2201554
            SpawnNpc(
                modelId: 2201554,
                name: "NPC_2201554",
                mapId: 6,
                zoneId: 38656,
                x: 414,
                y: 299,
                direction: 6,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133693, ModelID: 2201554
            SpawnNpc(
                modelId: 2201554,
                name: "NPC_2201554",
                mapId: 6,
                zoneId: 38656,
                x: 270,
                y: 295,
                direction: 6,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133698, ModelID: 2201554
            SpawnNpc(
                modelId: 2201554,
                name: "NPC_2201554",
                mapId: 6,
                zoneId: 38656,
                x: 256,
                y: 186,
                direction: 6,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133703, ModelID: 2201553
            SpawnNpc(
                modelId: 2201553,
                name: "NPC_2201553",
                mapId: 6,
                zoneId: 38656,
                x: 244,
                y: 186,
                direction: 7,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133708, ModelID: 2201524
            SpawnNpc(
                modelId: 2201524,
                name: "NPC_2201524",
                mapId: 6,
                zoneId: 38656,
                x: 267,
                y: 201,
                direction: 6,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133713, ModelID: 2201551
            SpawnNpc(
                modelId: 2201551,
                name: "NPC_2201551",
                mapId: 6,
                zoneId: 38656,
                x: 285,
                y: 239,
                direction: 3,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133718, ModelID: 2201552
            SpawnNpc(
                modelId: 2201552,
                name: "NPC_2201552",
                mapId: 6,
                zoneId: 38656,
                x: 336,
                y: 270,
                direction: 6,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133723, ModelID: 2201550
            SpawnNpc(
                modelId: 2201550,
                name: "NPC_2201550",
                mapId: 6,
                zoneId: 38656,
                x: 333,
                y: 268,
                direction: 4,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133728, ModelID: 2201541
            SpawnNpc(
                modelId: 2201541,
                name: "NPC_2201541",
                mapId: 6,
                zoneId: 38656,
                x: 307,
                y: 177,
                direction: 6,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133733, ModelID: 2201540
            SpawnNpc(
                modelId: 2201540,
                name: "NPC_2201540",
                mapId: 6,
                zoneId: 38656,
                x: 334,
                y: 261,
                direction: 4,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133738, ModelID: 2201538
            SpawnNpc(
                modelId: 2201538,
                name: "NPC_2201538",
                mapId: 6,
                zoneId: 38656,
                x: 278,
                y: 233,
                direction: 4,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133743, ModelID: 2201539
            SpawnNpc(
                modelId: 2201539,
                name: "NPC_2201539",
                mapId: 6,
                zoneId: 38656,
                x: 314,
                y: 238,
                direction: 6,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133748, ModelID: 2201537
            SpawnNpc(
                modelId: 2201537,
                name: "NPC_2201537",
                mapId: 6,
                zoneId: 38656,
                x: 232,
                y: 244,
                direction: 4,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133753, ModelID: 2201536
            SpawnNpc(
                modelId: 2201536,
                name: "NPC_2201536",
                mapId: 6,
                zoneId: 38656,
                x: 243,
                y: 231,
                direction: 4,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133758, ModelID: 2201535
            SpawnNpc(
                modelId: 2201535,
                name: "NPC_2201535",
                mapId: 6,
                zoneId: 38656,
                x: 292,
                y: 291,
                direction: 6,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133763, ModelID: 2201534
            SpawnNpc(
                modelId: 2201534,
                name: "NPC_2201534",
                mapId: 6,
                zoneId: 38656,
                x: 303,
                y: 280,
                direction: 6,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133768, ModelID: 2201533
            SpawnNpc(
                modelId: 2201533,
                name: "NPC_2201533",
                mapId: 6,
                zoneId: 38656,
                x: 242,
                y: 299,
                direction: 4,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133773, ModelID: 2201532
            SpawnNpc(
                modelId: 2201532,
                name: "NPC_2201532",
                mapId: 6,
                zoneId: 38656,
                x: 229,
                y: 283,
                direction: 6,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133778, ModelID: 2202786
            SpawnNpc(
                modelId: 2202786,
                name: "NPC_2202786",
                mapId: 6,
                zoneId: 38656,
                x: 358,
                y: 258,
                direction: 4,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133783, ModelID: 2201383
            SpawnNpc(
                modelId: 2201383,
                name: "NPC_2201383",
                mapId: 6,
                zoneId: 38656,
                x: 234,
                y: 291,
                direction: 5,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133856, ModelID: 2201526
            SpawnNpc(
                modelId: 2201526,
                name: "NPC_2201526",
                mapId: 6,
                zoneId: 38656,
                x: 265,
                y: 312,
                direction: 6,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133861, ModelID: 2201527
            SpawnNpc(
                modelId: 2201527,
                name: "NPC_2201527",
                mapId: 6,
                zoneId: 38656,
                x: 302,
                y: 175,
                direction: 4,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 133866, ModelID: 2201525
            SpawnNpc(
                modelId: 2201525,
                name: "NPC_2201525",
                mapId: 6,
                zoneId: 38656,
                x: 248,
                y: 139,
                direction: 4,
                dialogFunc: null  // TODO: Add dialog
            );

        }
    }
}
