// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 13:04:07
// NPCs for Map 6, Zone 38144

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Npcs
{
    /// <summary>
    /// NPCs for Map 6, Zone 38144
    /// </summary>
    public class Map6_Zone38144_Npcs : NpcScript
    {
        public override void Load()
        {
            // ObjectID: 73266, ModelID: 2201549
            SpawnNpc(
                modelId: 2201549,
                name: "NPC_2201549",
                mapId: 6,
                zoneId: 38144,
                x: 108,
                y: 136,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 73271, ModelID: 2201548
            SpawnNpc(
                modelId: 2201548,
                name: "NPC_2201548",
                mapId: 6,
                zoneId: 38144,
                x: 100,
                y: 133,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 73276, ModelID: 2201547
            SpawnNpc(
                modelId: 2201547,
                name: "NPC_2201547",
                mapId: 6,
                zoneId: 38144,
                x: 115,
                y: 132,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 73281, ModelID: 2201546
            SpawnNpc(
                modelId: 2201546,
                name: "NPC_2201546",
                mapId: 6,
                zoneId: 38144,
                x: 111,
                y: 124,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 73286, ModelID: 2201545
            SpawnNpc(
                modelId: 2201545,
                name: "NPC_2201545",
                mapId: 6,
                zoneId: 38144,
                x: 102,
                y: 127,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 73291, ModelID: 2201544
            SpawnNpc(
                modelId: 2201544,
                name: "NPC_2201544",
                mapId: 6,
                zoneId: 38144,
                x: 105,
                y: 121,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 73296, ModelID: 2201543
            SpawnNpc(
                modelId: 2201543,
                name: "NPC_2201543",
                mapId: 6,
                zoneId: 38144,
                x: 108,
                y: 130,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 73301, ModelID: 2201542
            SpawnNpc(
                modelId: 2201542,
                name: "NPC_2201542",
                mapId: 6,
                zoneId: 38144,
                x: 117,
                y: 126,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 73306, ModelID: 2201520
            SpawnNpc(
                modelId: 2201520,
                name: "NPC_2201520",
                mapId: 6,
                zoneId: 38144,
                x: 129,
                y: 128,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

		}
	}
}
