// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 14:16:02
// NPCs for Map 7, Zone 1536

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Npcs
{
    /// <summary>
    /// NPCs for Map 7, Zone 1536
    /// </summary>
    public class Map7_Zone1536_Npcs : NpcScript
    {
        public override void Load()
        {
            // ObjectID: 169043, ModelID: 2201602
            SpawnNpc(
                modelId: 2201602,
                name: "NPC_2201602",
                mapId: 7,
                zoneId: 1536,
                x: 127,
                y: 114,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 169048, ModelID: 2201593
            SpawnNpc(
                modelId: 2201593,
                name: "NPC_2201593",
                mapId: 7,
                zoneId: 1536,
                x: 123,
                y: 152,
                direction: 1,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 169121, ModelID: 2201592
            SpawnNpc(
                modelId: 2201592,
                name: "NPC_2201592",
                mapId: 7,
                zoneId: 1536,
                x: 126,
                y: 119,
                direction: 1,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 169126, ModelID: 2201591
            SpawnNpc(
                modelId: 2201591,
                name: "NPC_2201591",
                mapId: 7,
                zoneId: 1536,
                x: 131,
                y: 131,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 1480478229, ModelID: 2105070
            SpawnNpc(
                modelId: 2105070,
                name: "NPC_2105070",
                mapId: 7,
                zoneId: 1536,
                x: 109,
                y: 115,
                direction: 1,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 1390497301, ModelID: 2105071
            SpawnNpc(
                modelId: 2105071,
                name: "NPC_2105071",
                mapId: 7,
                zoneId: 1536,
                x: 112,
                y: 128,
                direction: 1,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 2731294520, ModelID: 2105070
            SpawnNpc(
                modelId: 2105070,
                name: "NPC_2105070",
                mapId: 7,
                zoneId: 1536,
                x: 166,
                y: 162,
                direction: 1,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 3925360440, ModelID: 2105071
            SpawnNpc(
                modelId: 2105071,
                name: "NPC_2105071",
                mapId: 7,
                zoneId: 1536,
                x: 116,
                y: 121,
                direction: 1,
                dialogFunc: null  // TODO: Add dialog
            );

        }
    }
}
