// Auto-generated by TalesWeaver Map Converter
// Generated: 2026-02-16 13:04:07
// NPCs for Map 7, Zone 3328

using Kakia.TW.World.Scripting;

namespace Kakia.TW.World.Scripts.Npcs
{
    /// <summary>
    /// NPCs for Map 7, Zone 3328
    /// </summary>
    public class Map7_Zone3328_Npcs : NpcScript
    {
        public override void Load()
        {
            // ObjectID: 386002653, ModelID: 38689
            SpawnNpc(
                modelId: 38689,
                name: "NPC_38689",
                mapId: 7,
                zoneId: 3328,
                x: 102,
                y: 1389,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

            // ObjectID: 947122717, ModelID: 38689
            SpawnNpc(
                modelId: 38689,
                name: "NPC_38689",
                mapId: 7,
                zoneId: 3328,
                x: 102,
                y: 1389,
                direction: 0,
                dialogFunc: null  // TODO: Add dialog
            );

        }
    }
}
